// Command genfont converts a raw VGA text-mode font ROM into a Go source file
// holding a [256][height]byte array.
//
// The input may be a raw binary (256*height bytes) or a C header (.h), from
// which the 0xNN byte literals are read in order. Each byte is one glyph
// scanline; the most significant bit is the leftmost pixel.
//
//	go run ./internal/genfont -in internal/genfont/3dfx8x16.bin -out font3dfx.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	in := flag.String("in", "3dfx8x16.bin", "input font file (.bin raw or .h header)")
	out := flag.String("out", "font3dfx.go", "output Go file")
	name := flag.String("name", "font3dfx", "generated variable name")
	pkg := flag.String("pkg", "vgarender", "package name")
	height := flag.Int("height", 16, "scanlines per glyph")
	flag.Parse()

	if err := run(*in, *out, *name, *pkg, *height); err != nil {
		fmt.Fprintln(os.Stderr, "genfont:", err)
		os.Exit(1)
	}
}

func run(in, out, name, pkg string, height int) error {
	raw, err := os.ReadFile(in) // #nosec G304 -- in is a developer-supplied path to a trusted local font file
	if err != nil {
		return err
	}

	data, err := decode(in, raw)
	if err != nil {
		return err
	}

	want := 256 * height
	if len(data) != want {
		return fmt.Errorf("expected %d bytes (256 glyphs x %d scanlines), got %d", want, height, len(data))
	}

	src, err := render(data, name, pkg, height)
	if err != nil {
		return err
	}

	return os.WriteFile(out, src, 0o644) // #nosec G306 -- generated Go source is meant to be world-readable
}

var hexByte = regexp.MustCompile(`0[xX][0-9a-fA-F]{2}`)

// decode returns the raw glyph bytes. A .h input is scanned for 0xNN literals;
// anything else is treated as a raw binary.
func decode(name string, raw []byte) ([]byte, error) {
	if !strings.HasSuffix(name, ".h") {
		return raw, nil
	}

	tokens := hexByte.FindAll(raw, -1)
	out := make([]byte, len(tokens))
	for i, tok := range tokens {
		v, err := strconv.ParseUint(string(tok[2:]), 16, 8)
		if err != nil {
			return nil, err
		}
		out[i] = byte(v)
	}
	return out, nil
}

func render(data []byte, name, pkg string, height int) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprint(&b, "// Code generated by internal/genfont; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// %s is a VGA text-mode font: 256 glyphs of %d scanlines each.\n", name, height)
	fmt.Fprint(&b, "// Each byte is one scanline; the most significant bit is the leftmost pixel.\n")
	fmt.Fprintf(&b, "var %s = [256][%d]byte{\n", name, height)
	for g := range 256 {
		b.WriteString("\t{")
		for r := range height {
			if r > 0 {
				b.WriteByte(' ')
			}
			fmt.Fprintf(&b, "0x%02x,", data[g*height+r])
		}
		fmt.Fprintf(&b, "}, // 0x%02x\n", g)
	}
	b.WriteString("}\n")

	return format.Source(b.Bytes())
}
